services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus/config
      - ./database:/prometheus/database
    command:
      - "--config.file=/etc/prometheus/config/prometheus.yml"
      - "--storage.tsdb.path=/prometheus/database"
      - "--storage.tsdb.retention.time=30d"
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: docker.io/grafana/grafana:latest-ubuntu
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
